<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WhisperSelectGenSubs</RootNamespace>
    <AssemblyName>WhisperSelectGenSubs</AssemblyName>
    <Version>1.0.5</Version>
    <AssemblyVersion>1.0.5.0</AssemblyVersion>
    <FileVersion>1.0.5.0</FileVersion>
  </PropertyGroup>
</Project>
